# Generated by Django 5.2.1 on 2025-06-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
    ]
