# Generated by Django 5.2.1 on 2025-06-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_entry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at']},
        ),
    ]
