# Generated by Django 5.2.1 on 2025-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadedimage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='item_type',
            field=models.CharField(choices=[('entry', 'Entry'), ('comment', 'Comment'), ('like', 'Like'), ('follow', 'Follow Request'), ('report', 'Report')], max_length=20),
        ),
    ]
