# Generated by Django 5.2.1 on 2025-06-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_inbox_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Image data stored as blob', null=True),
        ),
    ]
