# Generated by Django 5.2.1 on 2025-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_update_visibility_to_uppercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.TextField(blank=True, help_text='Profile image as data URL or regular URL'),
        ),
    ]
