# Generated by Django 5.2.1 on 2025-07-14 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_author_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_entries', to=settings.AUTH_USER_MODEL, to_field='url')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.entry', to_field='url')),
            ],
            options={
                'indexes': [models.Index(fields=['entry', 'created_at'], name='app_saveden_entry_i_fc9b2d_idx'), models.Index(fields=['author', 'created_at'], name='app_saveden_author__1e3cde_idx'), models.Index(fields=['created_at'], name='app_saveden_created_526179_idx'), models.Index(fields=['entry'], name='app_saveden_entry_i_ac43cf_idx'), models.Index(fields=['author'], name='app_saveden_author__dfa242_idx')],
                'unique_together': {('author', 'entry')},
            },
        ),
    ]
