# Generated by Django 5.2.1 on 2025-07-14 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_savedentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.entry'),
        ),
    ]
