# Generated by Django 5.2.1 on 2025-07-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_add_categories_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
