# Generated by Django 5.2.1 on 2025-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_author_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
