# Generated by Django 5.2.1 on 2025-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_author_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fqid',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
