# Generated by Django 5.2.1 on 2025-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_entry_fqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('requesting', 'Requesting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requesting', max_length=10),
        ),
    ]
