# Generated by Django 5.2.1 on 2025-07-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_follow_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedEntry',
        ),
    ]
