# Generated by Django 5.2.1 on 2025-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_savedentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png', 'PNG Image'), ('image/jpeg', 'JPEG Image'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)'), ('application/base64', 'Base64 Data')], default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png', 'PNG Image'), ('image/jpeg', 'JPEG Image'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)'), ('application/base64', 'Base64 Data')], default='text/plain', max_length=50),
        ),
    ]
