# Generated by Django 5.2.1 on 2025-07-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_comment_content_type_alter_entry_content_type'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-published', '-created_at'], 'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveIndex(
            model_name='author',
            name='app_author_display_05766b_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='app_entry_visibil_2c2ba8_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='app_entry_author__4fd841_idx',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='app_entry_updated_e50771_idx',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='display_name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='profile_image',
            new_name='profileImage',
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['displayName'], name='app_author_display_e46bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['visibility', 'published'], name='app_entry_visibil_7ea1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'published'], name='app_entry_author__49d55b_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['published'], name='app_entry_publish_1efe2e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['-published'], name='app_entry_publish_8de45a_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'visibility', 'published'], name='app_entry_author__ef55e6_idx'),
        ),
    ]
