# Generated by Django 5.2.1 on 2025-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_entry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
