# Generated by Django 5.2.1 on 2025-07-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_author_location_remove_author_website_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
