# Generated by Django 5.2.1 on 2025-07-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
