# Generated by Django 5.2.1 on 2025-07-30 22:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_author_bio'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('entry', 'Entry'), ('follow', 'Follow Request'), ('like', 'Like'), ('comment', 'Comment')], max_length=20)),
                ('object_id', models.UUIDField()),
                ('is_read', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(help_text='Original JSON data received from remote node')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL, to_field='url')),
            ],
            options={
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['recipient', 'activity_type'], name='app_inbox_recipie_6e1c8d_idx'), models.Index(fields=['recipient', 'is_read'], name='app_inbox_recipie_93b8fa_idx'), models.Index(fields=['delivered_at'], name='app_inbox_deliver_50e15d_idx'), models.Index(fields=['content_type', 'object_id'], name='app_inbox_content_c6c173_idx')],
                'unique_together': {('recipient', 'content_type', 'object_id')},
            },
        ),
    ]
