# Generated by Django 5.2.1 on 2025-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_inbox'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inbox',
            name='app_inbox_content_c6c173_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inbox',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inbox',
            name='object_data',
            field=models.JSONField(default=2, help_text='The actual object (Entry, Follow, Like, Comment) in JSON format'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inbox',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='Original JSON data received from remote node', null=True),
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='object_id',
        ),
    ]
