# Generated by Django 5.2.1 on 2025-07-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_inbox_app_inbox_content_c6c173_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='object_data',
            field=models.JSONField(default=dict, help_text='The actual object (Entry, Follow, Like, Comment) in JSON format'),
        ),
    ]
