# Generated by Django 5.2.1 on 2025-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_inbox_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.TextField(blank=True, default='', help_text='Profile image as data URL or regular URL'),
        ),
    ]
