# Generated by Django 5.2.1 on 2025-08-04 19:57

from django.db import migrations


def convert_null_to_empty_string(apps, schema_editor):
    """Convert any null values to empty strings for github_username and profileImage"""
    Author = apps.get_model('app', 'Author')
    
    # Update null github_username values to empty string
    Author.objects.filter(github_username__isnull=True).update(github_username='')
    # Update null profileImage values to empty string  
    Author.objects.filter(profileImage__isnull=True).update(profileImage='')


def reverse_convert_null_to_empty_string(apps, schema_editor):
    """Reverse operation - convert empty strings back to null"""
    Author = apps.get_model('app', 'Author')
    
    # Convert empty strings back to null for reverse migration
    Author.objects.filter(github_username='').update(github_username=None)
    Author.objects.filter(profileImage='').update(profileImage=None)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_author_displayname_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_null_to_empty_string,
            reverse_convert_null_to_empty_string,
        ),
    ]
